version: 2.1

jobs:
  install_dep:
    docker:
      - image: cimg/python:3.10.1
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install pipenv
            pipenv install --dev
            pipenv run python manage.py migrate
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Tests
          command: |
            pip install --upgrade pip
            pip install xmlrunner
            pipenv run pytest
          environment:
            DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  tag:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Create Git Tag
          command: |
            git tag -a "v1.0.${CIRCLE_BUILD_NUM}" -m "Version 1.0.${CIRCLE_BUILD_NUM}" ${CIRCLE_SHA1}
            git push origin "v1.0.${CIRCLE_BUILD_NUM}"

workflows:
  version: 2
  on_commit:
    jobs:
      - install_dep
      - build_and_test:
          requires:
            - install_dep
      
      - tag:
          requires:
            - build_and_test
          filters:
            branches:
              only: master

